title: Interactive AC Troubleshooting Guide
description: An interactive tool to diagnose automotive AC issues based on gauge readings.
baseurl: "/interactiveACguide" # If hosted at the root of your GitHub Pages site (e.g., username.github.io/repository-name/), set this to "/repository-name"
url: "alextheberge.github.io" # Your site's full URL (e.g., https://username.github.io)

# Optional: Specify a theme or use `theme: null` if Tailwind handles everything.
# For GitHub Pages, it defaults to Primer if no theme is set.
# theme: minima
# theme: null # If you want to ensure only your Tailwind/custom styles apply.

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md